recipes/urls.py
from django.urls import path
from meals import views as meal_views

from . import views

app_name = "recipes"

urlpatterns = [
    path("", views.recipe_list_view, name="recipe_list"),
    path("create/", views.recipe_create_view, name="create_view"),
    path(
        "meal-toggle/<int:recipe_id>/",
        meal_views.meal_queue_toggle_view,
        name="meal_toggle",
    ),
    path("update/<int:id>/", views.recipe_update_view, name="update_view"),
    path("detail/<int:id>/", views.recipe_detail_view, name="detail_view"),
    path("delete/<int:id>/", views.recipe_delete_view, name="delete"),
    path(
        "upload-image/<int:parent_id>/",
        views.recipe_ingredient_image_upload_view,
        name="upload_image",
    ),
    path(
        "<int:parent_id>/ingredient/<int:id>/",
        views.recipe_ingredient_delete_view,
        name="ingredient_delete",
    ),
    path(
        "hx/<int:parent_id>/ingredient/<int:id>/",
        views.recipe_ingredient_update_hx_view,
        name="ingredient_update_hx",
    ),
    path(
        "hx/<int:parent_id>/ingredient/",
        views.recipe_ingredient_update_hx_view,
        name="ingredient_create_hx",
    ),
    path("hx/<int:id>/", views.recipe_detail_hx_view, name="detail_hx"),
]

search/urls.py
from django.urls import path

from . import views as search_views

urlpatterns = [
    path("", search_views.search_view),
]

trydjango/urls.py
from django.contrib import admin
from django.urls import include, path
from users.views import login_view, logout_view, register_view

urlpatterns = [
    path("", include("articles.urls")),
    path("search/", include("search.urls")),
    path("recipes/", include("recipes.urls")),
    path("login/", login_view),
    path("logout/", logout_view),
    path("register/", register_view),
    path("admin/", admin.site.urls),
]

recipes/models.py
import pathlib
import uuid

import pint
from django.db import models
from django.db.models import Q
from django.urls import reverse
from users.models import User

from .utils import number_str_to_float
from .validators import validate_unit_of_measure


class RecipeQuerySet(models.QuerySet):
    def search(self, query=None):
        if query is None or query == "":
            return self.none()
        # lookups = (active=True)
        lookups = (
            Q(name__icontains=query)
            | Q(description__icontains=query)
            | Q(directions__icontains=query)
        )
        return self.filter(lookups)


class RecipeManager(models.Manager):
    def get_queryset(self):
        return RecipeQuerySet(self.model, using=self._db)

    def search(self, query=None):
        return self.get_queryset().search(query=query)


class Recipe(models.Model):
    user = models.ForeignKey(
        User,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
    )
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    directions = models.TextField(blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=False)

    objects = RecipeManager()

    @property
    def title(self):
        return self.name

    def get_absolute_url(self):
        return reverse("recipes:detail_view", kwargs={"id": self.id})

    def get_hx_url(self):
        return reverse("recipes:detail_hx", kwargs={"id": self.id})

    def get_update_url(self):
        return reverse("recipes:update_view", kwargs={"id": self.id})

    def get_delete_url(self):
        return reverse("recipes:delete", kwargs={"id": self.id})

    def get_image_upload_url(self):
        kwarg = {"parent_id": self.id}
        return reverse("recipes:upload_image", kwargs=kwarg)

    def get_ingredients_children(self):
        return self.recipeingredient_set.all()

    class Meta:
        db_table = "recipe_recipe"

    def __str__(self):
        return f"{self.id} | {self.name}"


def recipe_ingredient_image_upload_handler(instance, filename):
    fpath = pathlib.Path(filename)
    new_fname = str(uuid.uuid1())
    return f"recipes/ingredient/{new_fname}{fpath.suffix}"


class RecipeIngredientImage(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=recipe_ingredient_image_upload_handler)
    extracted = models.JSONField(blank=True, null=True)


class RecipeIngredient(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    quantity = models.CharField(max_length=50, blank=True, null=True)
    quantity_as_float = models.FloatField(blank=True, null=True)
    unit = models.CharField(
        max_length=50, validators=[validate_unit_of_measure]
    )
    directions = models.TextField(blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    def convert_to_system(self, system="mks"):
        if self.quantity_as_float is None:
            return None
        ureg = pint.UnitRegistry(system=system)
        measurement = self.quantity_as_float * ureg[self.unit.lower()]
        print(measurement)
        return measurement  # .to_base_units()

    def as_mks(self):
        measurement = self.convert_to_system(system="mks")
        print(measurement)
        return measurement.to_base_units()

    def as_imperial(self):
        measurement = self.convert_to_system(system="imperial")
        print(measurement)
        return measurement.to_base_units()

    def save(self, *args, **kwargs):
        qty = self.quantity
        qty_as_float, qty_as_float_success = number_str_to_float(qty)
        if qty_as_float_success:
            self.quantity_as_float = qty_as_float
        else:
            self.quantity_as_float = None
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return self.recipe.get_absolute_url()

    def get_delete_url(self):
        kwarg = {"parent_id": self.recipe.id, "id": self.id}
        return reverse("recipes:ingredient_delete", kwargs=kwarg)

    def get_hx_edit_url(self):
        kwarg = {"parent_id": self.recipe.id, "id": self.id}
        return reverse("recipes:ingredient_update_hx", kwargs=kwarg)

    class Meta:
        db_table = "recipe_recipe_ingredient"

    def __str__(self):
        return f"{self.id} | {self.name}"

recipes/forms.py
from django import forms

from .models import Recipe, RecipeIngredient, RecipeIngredientImage


class RecipeForm(forms.ModelForm):
    error_css_class = "error-field"
    required_css_class = "required-field"
    name = forms.CharField(help_text="Texto de ajuda!")

    class Meta:
        model = Recipe
        fields = ["name", "description", "directions"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            new_data = {
                "placeholder": f"Receita {str(field)}",
                "class": "form-control",
            }
            self.fields[str(field)].widget.attrs.update(new_data)
            self.fields[str(field)].label = ""

        self.fields["description"].widget.attrs.update({"rows": "2"})
        self.fields["directions"].widget.attrs.update({"rows": "4"})


class RecipeIngredientForm(forms.ModelForm):
    class Meta:
        model = RecipeIngredient
        fields = ["name", "quantity", "unit"]


class RecipeIngredientImageForm(forms.ModelForm):
    class Meta:
        model = RecipeIngredientImage
        fields = ["image"]
        labels = {"image": "Extrair os ingredientes via upload imagem"}

recipes/views.py
from django.contrib.auth.decorators import login_required
from django.forms.models import modelformset_factory
from django.http import Http404, HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from .forms import RecipeForm, RecipeIngredientForm, RecipeIngredientImageForm
from .models import Recipe, RecipeIngredient
from .services import extract_text_via_ocr_service
from .utils import convert_to_qty_units, parce_paragraph_to_recipe_line


@login_required
def recipe_list_view(request):
    qs = Recipe.objects.filter(user=request.user)
    context = {"object_list": qs}
    return render(request, "recipes/list.html", context)


@login_required
def recipe_detail_view(request, id=None):
    hx_url = reverse("recipes:detail_hx", kwargs={"id": id})
    context = {"hx_url": hx_url}
    return render(request, "recipes/detail.html", context)


@login_required
def recipe_delete_view(request, id=None):
    try:
        obj = Recipe.objects.get(id=id, user=request.user)
    except Exception as e:
        print(e)
        obj = None
    if obj is None:
        if request.htmx:
            return HttpResponse("Não Encontrado")
        raise Http404
    if request.method == "POST":
        obj.active = False
        obj.save()
        success_url = reverse("recipes:recipe_list")
        if request.htmx:
            headers = {"HX-Redirect": success_url}
            return HttpResponse("Deletado", headers=headers)
        return redirect(success_url)
    context = {"object": obj}
    return render(request, "recipes/delete.html", context)


@login_required
def recipe_ingredient_delete_view(request, parent_id=None, id=None):
    try:
        obj = RecipeIngredient.objects.get(
            recipe__id=parent_id, id=id, recipe__user=request.user
        )
    except Exception as e:
        print(e)
        obj = None
    if obj is None:
        if request.htmx:
            return HttpResponse("Não Encontrado")
        raise Http404
    if request.method == "POST":
        name = obj.name
        obj.active = False
        obj.save()
        success_url = reverse("recipes:detail_view", kwargs={"id": parent_id})
        if request.htmx:
            # headers = {"HX-Redirect": success_url}
            # return HttpResponse("<span style='color: #ccc';>Deletado<span>")
            return render(
                request,
                "recipes/partials/ingredient-inline-delete-response.html",
                {"name": name},
            )
        return redirect(success_url)
    context = {"object": obj}
    return render(request, "recipes/delete.html", context)


@login_required
def recipe_detail_hx_view(request, id=None):
    if not request.htmx:
        raise Http404
    try:
        obj = Recipe.objects.get(id=id, user=request.user)
    except Exception as e:
        print(e)
        obj = None
    if obj is None:
        return HttpResponse("Não encontrado")
    context = {"object": obj}
    return render(request, "recipes/partials/detail.html", context)


@login_required
def recipe_create_view(request):
    form = RecipeForm(request.POST or None)
    context = {"form": form}
    if form.is_valid():
        obj = form.save(commit=False)
        obj.user = request.user
        obj.active = True
        obj.save()
        if request.htmx:
            headers = {"HX-Redirect": obj.get_absolute_url()}
            return HttpResponse("Criado", headers=headers)
        return redirect(obj.get_absolute_url())
    return render(request, "recipes/create-update.html", context)


@login_required
def recipe_update_view(request, id=None):
    obj = get_object_or_404(Recipe, id=id, user=request.user)
    form = RecipeForm(request.POST or None, instance=obj)
    new_ingredient_url = reverse(
        "recipes:ingredient_create_hx", kwargs={"parent_id": obj.id}
    )
    context = {
        "form": form,
        "object": obj,
        "new_ingredient_url": new_ingredient_url,
    }
    if form.is_valid():
        form.save()
        context["message"] = "Atualizado com sucesso!"
    if request.htmx:
        return render(request, "recipes/partials/forms.html", context)
    return render(request, "recipes/create-update.html", context)


@login_required
def recipe_ingredient_update_hx_view(request, parent_id=None, id=None):
    if not request.htmx:
        raise Http404
    try:
        parent_obj = Recipe.objects.get(id=parent_id, user=request.user)
    except Exception as e:
        print(e)
        parent_obj = None
    if parent_obj is None:
        return HttpResponse("Não encontrado")

    instance = None

    if id is not None:
        try:
            instance = RecipeIngredient.objects.get(recipe=parent_obj, id=id)
        except Exception as e:
            print(e)
            instance = None
    form = RecipeIngredientForm(request.POST or None, instance=instance)
    url = reverse(
        "recipes:ingredient_create_hx", kwargs={"parent_id": parent_obj.id}
    )
    if instance:
        url = instance.get_hx_edit_url()

    context = {"object": instance, "form": form, "url": url}
    if form.is_valid():
        new_obj = form.save(commit=False)
        if instance is None:
            new_obj.recipe = parent_obj
        new_obj.save()
        context["object"] = new_obj
        return render(
            request, "recipes/partials/ingredient-inline.html", context
        )
    return render(request, "recipes/partials/ingredient-form.html", context)


def recipe_ingredient_image_upload_view(request, parent_id=None):
    template_name = "recipes/upload-image.html"
    if request.htmx:
        template_name = "recipes/partials/image-upload-form.html"
    try:
        parent_obj = Recipe.objects.get(id=parent_id, user=request.user)
    except Exception as e:
        print(e)
        parent_obj = None
    if parent_obj is None:
        raise Http404
    form = RecipeIngredientImageForm(
        request.POST or None, request.FILES or None
    )
    if form.is_valid():
        obj = form.save(commit=False)
        obj.recipe = parent_obj
        obj.save()
        extracted = extract_text_via_ocr_service(obj.image)
        obj.extracted = extracted
        obj.save()
        og = extracted["original"]
        results = parce_paragraph_to_recipe_line(og)
        dataset = convert_to_qty_units(results)
        new_objs = []
        for data in dataset:
            data["recipe_id"] = parent_id
            new_objs.append(RecipeIngredient(**data))
        RecipeIngredient.objects.bulk_create(new_objs)
        success_url = parent_obj.get_update_url()
        if request.htmx:
            headers = {"HX-Redirect": success_url}
            return HttpResponse("Atualizado", headers=headers)
    return render(request, template_name, {"form": form})

templates/recipes/create-update.html
{% extends 'base.html' %}

{% block content %}
<style>
    #empty-form {
        margin-top: 1em;
        margin-bottom: 1em;
    }

    .ingredient-form {
        border-bottom: 1px solid black;
        margin-top: 1em;
        margin-bottom: 1em;
    }

    .hidden {
        display: none
    }
</style>
<div class='row'>
    <div class='{% if object.id %}col-12 col-md-8{% else %}col-md-6 mx-auto{% endif %}'>
        {% if not object.id %}
            <h1>Criar Receita</h1>
        {% endif %}
        {% include 'recipes/partials/forms.html' %}
    </div>
    <div class='{% if object.id %}col-12 col-md-4{% else %}d-none{% endif %}'>
        <h3>Ingredientes</h3>
        {% for ingredient in object.get_ingredients_children %}
            {% include 'recipes/partials/ingredient-inline.html' with object=ingredient%}
        {% endfor %}
        {% if new_ingredient_url %}
            <div hx-get='{{ object.get_image_upload_url }}' hx-trigger='revealed'></div>
            <div id='ingredient-create'></div>
                <button
                    hx-get={{ new_ingredient_url }} hx-trigger='click'
                    hx-target='#ingredient-create' hx-swap='beforeend'
                >
                    Adicionar Ingrediente
                </button>
        {% endif %}
    </div>
</div>
{% endblock content %}

{% block script %}
    <script>
        //const addMoreBtn = document.getElementById('add-more')
        document.addEventListener('click', (event)=>{
            if (event.target.id == 'add-more') {
                add_new_form(event)
            }
        })
        //addMoreBtn.addEventListener('click', add_new_form)

        function add_new_form(event) {
            if (event) {
                event.preventDefault()
            }
            const totalNewForms = document.getElementById('id_form-TOTAL_FORMS')
            const currentIngredientForms = document.getElementsByClassName('ingredient-form')
            const currentFormCount = currentIngredientForms.length // + 1
            const formCopyTarget = document.getElementById('ingredient-form-list')
            const copyEmptyFormEl = document.getElementById('empty-form').cloneNode(true)
            copyEmptyFormEl.setAttribute('class', 'ingredient-form')
            copyEmptyFormEl.setAttribute('id', `form-${currentFormCount}`)
            const regex = new RegExp('__prefix__', 'g')
            copyEmptyFormEl.innerHTML = copyEmptyFormEl.innerHTML.replace(regex, currentFormCount)
            totalNewForms.setAttribute('value', currentFormCount + 1)
            formCopyTarget.append(copyEmptyFormEl)
        }
    </script>
{% endblock script %}

templates/recipes/delete.html
{% extends 'base.html' %}

{% block content %}

    {% if object %}
        <form action="." method='POST'>
            {% csrf_token %}
            <p>Tem certeza que deseja deletar: {{object.name}} ?</p>
            <button type='submit'>Sim, delete!</button>
        </form>
    {% endif %}

{% endblock content %}

templates/recipes/detail.html
{% extends 'base.html' %}

{% block content %}
<div hx-get='{{ hx_url }}' hx-trigger='revealed'>
    <div class='htmx-indicator'>Carregando</div>
</div>
{% endblock content %}

templates/recipes/list.html
{% extends 'base.html' %}

{% block content %}
    <h1>Minhas Receitas</h1>
    <h3>
        <a href='{% url "recipes:create_view" %}'>
            Novas Receitas
        </a>
    </h3>
    <hr/>

    <ul>
        {% for x in object_list %}
            {% if x.name %}
                <div class='mb-2'>
                    <a class='lead' href="{{ x.get_absolute_url }}">
                        {{ x.name }}
                    </a>
                    <div hx-get='{% url "recipes:meal_toggle" recipe_id=x.id %}'
                        hx-trigger='revealed'
                    >
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </ul>
{% endblock content %}

templates/recipes/upload-image.html
{% extends 'base.html' %}

{% block content %}
    {% include 'recipes/partials/image-upload-form.html' %}
{% endblock content %}